### PR TITLE
Prettify SDK Pages

### PR DESCRIPTION
**Pull request by andrewdmaclean**
image

### CODE REVIEW

**Comment by suthar26** [comment]
this is how it looks in dark mode
Screenshot 2023-04-20 at 7 23 31 PM

**Comment by andrewdmaclean** [comment]
Hey @suthar26 not sure which part you are calling out - s it the blue links?

If so, thats across all the docs and something I think which will need to be more widely resolved.

**Comment by andrewdmaclean** [comment]
@aurorawalker @VicV this was a request that come from y'all so wondering what you think?

**Comment by suthar26** [comment]
@andrewdmaclean sorry I thought the Tip looked different but I was thinking of the TODO, sorry for the confusion, looks good :)

**Comment by andrewdmaclean** [comment]
Whenever we are able to merge then it looks like its good to go :)

**Pull request merged**
