### PR TITLE
fix: nodejs yarn install doc

### PR DESCRIPTION
**Pull request by jonathannorris**

### CODE REVIEW

**Comment by jonathannorris** [comment]
* **#586** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/devcycle-docs/586?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jonathannorris and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by JamieSinn — COMMENTED** [review]
Can we use the github code search queries to find this without having direct line refs?

**Comment by jonathannorris** [comment]
@JamieSinn got a link / example of that?

**Comment by JamieSinn** [comment]
https://github.com/search?q=repo%3ADevCycleHQ%2Fjs-sdks+export+interface+DevCycleUser+language%3ATypeScript&type=code

**Review by laurawarr — APPROVED** [review]

**Pull request merged**
