### PR TITLE
Update Overview Image

### PR DESCRIPTION
**Pull request by andrewdmaclean**
Updated Image:
devcycle-org-structure

### CODE REVIEW

**Comment by andrewdmaclean** [comment]
@leslie-lau fixed that issue - when you approve this can merge!

devcycle-org-structure

**Comment by leslie-lau** [comment]
@andrewdmaclean There's also the arrows from Environments to Users & Targeting that look off center

**Comment by andrewdmaclean** [comment]
@leslie-lau thanks for catching that - fixed!

**Review by leslie-lau — APPROVED** [review]
Looks good!

**Pull request merged**
