### PR TITLE
Create DevCycle Overview page

### PR DESCRIPTION
**Pull request by leslie-lau**
Add a new DevCycle overview page to the Essentials section and put it at position 1

### CODE REVIEW

**Comment by andrewdmaclean** [comment]
Hey @leslie-lau 👋  I left a bunch of comments over in Vercel and happy to talk through any of them! I really like the idea of basically a tl;dr page for all of the stuff that is going to be covered in the essentials section but maybe a few slight placement changes might be helpful?

**Review by andrewdmaclean — COMMENTED** [review]
I left a few notes over in Vecel! Let me know if you have any questions.

**Comment by leslie-lau** [comment]
@andrewdmaclean I made some changes based on your comments

**Comment by andrewdmaclean** [comment]
> @andrewdmaclean I made some changes based on your comments

Taking a look now!

**Review by andrewdmaclean — APPROVED** [review]

**Pull request merged**
